export * from './user.schema';
export * from './student.schema';
export * from './university.schema';
export * from './application.schema';
export * from './payment.schema';
export * from './document.schema';
export * from './payment-config.schema';
export * from './notification.schema';
export * from './accounting.schema';
